#define BIT(N) (1UL << N)
#define BIT_MASK(WIDTH) (BIT(WIDTH)-1)
#define BIT_EXTRACT(VALUE, POSITION, WIDTH) (((VALUE) >> (POSITION)) & BIT_MASK(WIDTH))

#define UNSIGNED_CHECK_FIT(VALUE, WIDTH) !((VALUE) & ~BIT_MASK(WIDTH))
#define SIGNED_CHECK_FIT(VALUE, WIDTH) UNSIGNED_CHECK_FIT((((VALUE) < 0) ? (-(VALUE) - 1) : (VALUE)), WIDTH-1)

#define UNSIGNED_SHRINK_TO(VALUE, WIDTH) BIT_EXTRACT(VALUE, 0, WIDTH)
#define SIGNED_SHRINK_TO(VALUE, WIDTH) (BIT_EXTRACT(VALUE, 0, WIDTH-1) | ((VALUE < 0) * BIT((WIDTH)-1)))

#define SIGN_BIT_SET(VALUE, WIDTH) !!((VALUE) & BIT(WIDTH-1))
#define SIGNED_EXTEND(VALUE, OLD_WIDTH) (SIGN_BIT_SET(VALUE, OLD_WIDTH) ? (VALUE) | ~BIT_MASK(OLD_WIDTH) : (VALUE))
